### PR TITLE
Url to text

### PR DESCRIPTION
**Pull request by guillaumeberthier**

### CODE REVIEW

**Comment by VictorNouvellet** [comment]
Could you rename urlToText to url_to_text before I accept your pull request please ?

**Comment by VictorNouvellet** [comment]
And, in this file, rename 'text' variable to 'apiUrl' ?

**Comment by VictorNouvellet** [comment]
Not sure everybody needs 'npm-debug.log' -> gitignore ;)

**Comment by ccanete** [comment]
Added to gitignore

**Comment by ccanete** [comment]
@V1C0D3R Les commentaires, mets les sur le code (onglet 'Files changed') sinon il faut chercher de quoi tu parles

**Pull request merged**
